name: build desktop

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows App (.exe)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Windows App
        env:
          VITE_API_URL: https://voice.sayago.ru
          VITE_GATEWAY_URL: wss://voice.sayago.ru
          VITE_WEB_URL: https://voice.sayago.ru
        run: pnpm --filter fluxer_desktop run build:win

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fluxer-Desktop-Windows
          path: |
            fluxer_desktop/dist/*.exe
            fluxer_desktop/release/*.exe
            fluxer_desktop/dist/*.zip
